module.exports = {
  value: [
    '<say-as interpret-as="interjection">あ〜あ</say-as>',
    '<say-as interpret-as="interjection">あちゃあ</say-as>',
    '<say-as interpret-as="interjection">あっはっは</say-as>',
    '<say-as interpret-as="interjection">あはは</say-as>',
    '<say-as interpret-as="interjection">あらあ</say-as>',
    '<say-as interpret-as="interjection">あらら</say-as>',
    '<say-as interpret-as="interjection">いゃ〜</say-as>',
    '<say-as interpret-as="interjection">うひゃあ</say-as>',
    '<say-as interpret-as="interjection">うふふ</say-as>',
    '<say-as interpret-as="interjection">うわ〜</say-as>',
    '<say-as interpret-as="interjection">え〜</say-as>',
    '<say-as interpret-as="interjection">おおー</say-as>',
    '<say-as interpret-as="interjection">くくく</say-as>',
    '<say-as interpret-as="interjection">ですね</say-as>',
    '<say-as interpret-as="interjection">なるほど</say-as>',
    '<say-as interpret-as="interjection">はぁ〜〜</say-as>',
    '<say-as interpret-as="interjection">はあて</say-as>',
    '<say-as interpret-as="interjection">ひいっ</say-as>',
    '<say-as interpret-as="interjection">ふぅ</say-as>',
    '<say-as interpret-as="interjection">ふふっ</say-as>',
    '<say-as interpret-as="interjection">ふうむ</say-as>',
    '<say-as interpret-as="interjection">へぇ</say-as>',
    '<say-as interpret-as="interjection">ほ〜</say-as>',
    '<say-as interpret-as="interjection">まぁ</say-as>',
    '<say-as interpret-as="interjection">わぁ</say-as>',
    '<say-as interpret-as="interjection">わおぅ</say-as>',
    '<say-as interpret-as="interjection">んも〜</say-as>',
  ],
};
